# Generated by Django 4.2.1 on 2023-11-30 12:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('dailyrecord_id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('measuredFood', models.CharField(max_length=100, null=True)),
                ('expectedQuantity', models.CharField(max_length=100, null=True)),
                ('foodName', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('total_amount', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
